version: "2"

services:
  mongo: 
    image: mongo:latest
    volumes: 
    - mongodata:/data/db
    ports: 
    - "27017:27017"
  mage:
    build: .
    image: mage:0.0.1-beta
    links:
    - mongo
    ports:
    - "4242:4242"
    depends_on:
    - "migrator"
    env_file:
    - mage.env
  migrator:
    image: mage:0.0.1-beta
    links:
    - mongo
    command: npm run migrate
    build: .
    depends_on:
    - "mongo"
volumes:
  mongodata:
